---
name: ESP Add-on
version: "7509f46"
slug: hass-addon-esp
description: Add-on to query the EskomSePush API
image: ghcr.io/kellerza/hass-addon-esp
startup: services
boot: auto
url: "https://github.com/kellerza/sunsynk/"
uart: false
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports: {}
ports_description: {}
host_network: false
map:
  - share:rw
options:
  AREAS:
    - API_KEY: "xxxxxxxx-xxxxxxxx-xxxxxxxx-xxxxxxxx"
      AREA_ID: "jhbcitypower3-2-victorypark"
      HA_PREFIX: "eskom_vp"
  MQTT_HOST: core-mosquitto
  MQTT_PORT: 1883
  MQTT_USERNAME: hass
  MQTT_PASSWORD: ""
schema:
  AREAS:
    - API_KEY: str
      HA_PREFIX: str
      AREA_ID: str
  MQTT_HOST: str
  MQTT_PORT: port
  MQTT_USERNAME: str
  MQTT_PASSWORD: password
  DEBUG: int(0,5)?
  SEARCH_AREA: str?
