---
name: Sunsynk Inverter Add-on (dev)
version: 2023.01.19-0.2.9
slug: hass-addon-sunsynk-dev
description: Add-on for the Sunsynk Inverter
startup: services
boot: auto
url: "https://github.com/kellerza/sunsynk"
uart: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports: {}
ports_description: {}
host_network: false
map:
  - share:rw
options:
  PORT: ""
  DEVICE: ""
  DRIVER: "umodbus"
  SUNSYNK_ID: "007"
  SENSOR_PREFIX: ""
  SENSORS:
    - total_pv_power
    - total_battery_charge
    - total_battery_discharge
    - total_grid_export
    - total_grid_import
    - battery_soc
  READ_SENSORS_BATCH_SIZE: 60
  NUMBER_ENTITY_MODE: "auto"
  PROFILES: []
  MODBUS_SERVER_ID: 1
  MQTT_HOST: core-mosquitto
  MQTT_PORT: 1883
  MQTT_USERNAME: hass
  MQTT_PASSWORD: ""
  DEBUG: 0
schema:
  PORT: str?
  DEVICE: device(subsystem=tty)?
  DRIVER: str?
  SUNSYNK_ID: str
  SENSOR_PREFIX: str
  SENSORS:
    - str
  READ_SENSORS_BATCH_SIZE: int?
  NUMBER_ENTITY_MODE: list(auto|box|slider)?
  PROFILES:
    - str
  MODBUS_SERVER_ID: int
  MQTT_HOST: str
  MQTT_PORT: port
  MQTT_USERNAME: str
  MQTT_PASSWORD: password
  DEBUG: int
