---
name: Sunsynk/Deye Inverter Add-on (multi)
version: 2023.08.06-0.4.0
slug: hass-addon-sunsynk-multi
description: Add-on for a Sunsynk/Deye branded Inverter
startup: services
boot: auto
url: "https://github.com/kellerza/sunsynk"
uart: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports: {}
ports_description: {}
host_network: false
map:
  - share:rw
options:
  DRIVER: "umodbus"
  INVERTERS:
    - SERIAL_NR: "007"
      HA_PREFIX: SS
      MODBUS_ID: 1
      DONGLE_SERIAL_NUMBER: "0"
      PORT: "tcp://homeassistant.local:502"
  SENSOR_DEFINITIONS: single-phase
  SENSORS:
    - total_pv_energy
    - total_battery_charge
    - total_battery_discharge
    - total_grid_export
    - total_grid_import
    - battery_soc
  SENSORS_FIRST_INVERTER: []
  MANUFACTURER: Sunsynk
  READ_SENSORS_BATCH_SIZE: 60
  NUMBER_ENTITY_MODE: "auto"
  MQTT_HOST: core-mosquitto
  MQTT_PORT: 1883
  MQTT_USERNAME: hass
  MQTT_PASSWORD: ""
  DEBUG: 0
  DEBUG_DEVICE: "/dev/ttyAMA0"
schema:
  DRIVER: list(pymodbus|umodbus|solarman)
  INVERTERS:
    - SERIAL_NR: str
      HA_PREFIX: str
      MODBUS_ID: int(1,16)
      DONGLE_SERIAL_NUMBER: str?
      PORT: str
  SENSOR_DEFINITIONS: list(single-phase|three-phase)
  SENSORS:
    - str
  SENSORS_FIRST_INVERTER:
    - str
  MANUFACTURER: str
  READ_SENSORS_BATCH_SIZE: int(1,100)
  NUMBER_ENTITY_MODE: list(auto|box|slider)
  MQTT_HOST: str
  MQTT_PORT: port
  MQTT_USERNAME: str
  MQTT_PASSWORD: password
  DEBUG: int(0,5)
  DEBUG_DEVICE: device(subsystem=tty)
