---
name: Sunsynk Inverter Add-on
version: 2022.02.10-0.1.2
slug: hass-addon-sunsynk
description: Add-on for the Sunsynk Inverter
startup: services
boot: auto
url: 'https://github.com/kellerza/sunsynk'
uart: true
arch:
    - aarch64
    - amd64
    - armhf
    - armv7
    - i386
ports: {}
ports_description: {}
host_network: false
map:
    - share:rw
options:
    PORT: /dev/ttyUSB0
    PORT_ADDRESS: ''
    PROFILES: 0
    SUNSYNK_ID: your_inverter_serial_number
    SENSORS:
        - total_pv_power
        - total_battery_charge
        - total_battery_discharge
        - total_grid_export
        - total_grid_import
        - battery_soc
    SENSOR_PREFIX: ''
    TIMEOUT: 10
    MQTT_HOST: core-mosquitto
    MQTT_PORT: 1883
    MQTT_USERNAME: hass
    MQTT_PASSWORD: ''
    DEBUG: 0
schema:
    PORT: str?
    PORT_ADDRESS: str?
    PROFILES: int
    SUNSYNK_ID: str
    SENSORS:
        - str
    SENSOR_PREFIX: str?
    TIMEOUT: int
    MQTT_HOST: str
    MQTT_PORT: port
    MQTT_USERNAME: str
    MQTT_PASSWORD: password
    DEBUG: int
