---
name: Sunsynk or Deye Inverter add-on (dev-edge)
description: Add-on for a Sunsynk/Deye branded Inverter
version: "4b2b8f3"
slug: hass-addon-sunsynk-edge
image: ghcr.io/kellerza/hass-addon-sunsynk-multi
url: "https://kellerza.github.io/sunsynk"
services: ["mqtt:need"]
hassio_api: true
hassio_role: homeassistant
init: false
uart: true
apparmor: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - share:rw
  - addon_config:rw
  - share:rw
options:
  DRIVER: "pymodbus"
  INVERTERS:
    - SERIAL_NR: "007"
      HA_PREFIX: SS
      MODBUS_ID: 1
      DONGLE_SERIAL_NUMBER: "0"
      PORT: "tcp://homeassistant.local:502"
  SENSOR_DEFINITIONS: single-phase
  SENSORS:
    - energy_management
    - power_flow_card
    - pv2_power
  SENSORS_FIRST_INVERTER:
    - settings
  MANUFACTURER: Sunsynk
  READ_ALLOW_GAP: 2
  READ_SENSORS_BATCH_SIZE: 20
  SCHEDULES:
    - KEY: W
      READ_EVERY: 5
      REPORT_EVERY: 60
      CHANGE_ANY: false
      CHANGE_BY: 80
      CHANGE_PERCENT: 0
  NUMBER_ENTITY_MODE: "auto"
  PROG_TIME_INTERVAL: 15
schema:
  DRIVER: list(pymodbus|umodbus|solarman)
  INVERTERS:
    - SERIAL_NR: str
      HA_PREFIX: str
      MODBUS_ID: int(1,16)
      DONGLE_SERIAL_NUMBER: str?
      PORT: str
  SENSOR_DEFINITIONS: list(single-phase|single-phase-16kw|three-phase|three-phase-hv)
  SENSOR_OVERRIDES:
    - "match(^[a-z_]+(.[a-z]+)?=-?([0-9]*\\.)?[0-9]+$)?"
  SENSORS:
    - str
  SENSORS_FIRST_INVERTER:
    - str
  MANUFACTURER: str
  READ_ALLOW_GAP: int(1,50)
  READ_SENSORS_BATCH_SIZE: int(1,100)
  SCHEDULES:
    - KEY: str
      READ_EVERY: int(1,3600)
      REPORT_EVERY: int(2,3600)
      CHANGE_ANY: bool?
      CHANGE_BY: int(0,3600)?
      CHANGE_PERCENT: int(0,500)?
  NUMBER_ENTITY_MODE: list(auto|box|slider)
  PROG_TIME_INTERVAL: list(5|10|15|30|45|60)?
  MQTT_CUSTOM: str?
  MQTT_HOST: str?
  MQTT_PORT: port?
  MQTT_USERNAME: str?
  MQTT_PASSWORD: password?
  DEBUG: int(0,5)?
  DEBUG_DEVICE: device(subsystem=tty)?
